---
title: "Background Report"
author: "Pavel"
output: pdf_document
---

Include libraries and settings

```{r echo=FALSE}
source("graphs.R")
source("collect_experiments.R")
options( warn = -1 )
```

We get a list of links to experiments results:

```{r echo=FALSE}
GOOGLE_SPREADSHEET_URL <-"https://docs.google.com/spreadsheets/d/1DR4_TytGVSE-KyaZGiSpRmd8Ep-wMotK1JxPcPkNBXg/edit#gid=0"
experiments <- collectFromGoogleSpreadsheet(GOOGLE_SPREADSHEET_URL)
experiments$evaluation_url <- as.character(experiments$evaluation_url)
```

## Experiments:

```{r echo=FALSE, fig.keep='all', fig.width=12, fig.height=12}
all_data <- FALSE
for (i in 0:2){
	title <- experiments[i*4+1,"title"]
	print(paste("####",title, sep=" "))
	gr <- list()
	for (j in 0:3){
		index <- (i * 4) + j + 1
		print(index)

		experiment <- collectFromGoogleSpreadsheet(experiments[index,"evaluation_url"])
		experiment <- reformatExperimentData(experiment,experiments[index,"job_id"],experiments[index,"title"],experiments[index,"condition"])
		experiment <- filterEvaluation(experiment)
		
		if (all_data == FALSE){
			all_data = experiment
		}else{
			all_data = rbind(all_data, experiment)
		}
	}
}
tl <- plotTimeline(all_data, faceting = T,tl_bar_detail_show = F)
print(tl)
pt <- plotDotsDurationVSIndexAccuracy(all_data, faceting = T)
print(pt)
hg <- plotHistogram(all_data, faceting = T)
print(hg)
cm <- plotCumulative(all_data, faceting = T)
print(cm)
```